spring:
  mail:
    password: iktjursvvemfgwbu
    username: Literaki.SKNI@gmail.com
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/Literaki'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
default-config:
