DROP TABLE IF EXISTS security.verification_token CASCADE;
CREATE TABLE security.verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP with time zone                NOT NULL,
    CONSTRAINT pk_verification_token PRIMARY KEY (id)
);

ALTER TABLE security.login
    ADD is_deleted BOOLEAN;

ALTER TABLE security.login
    ADD verification_token_id BIGINT;

ALTER TABLE security.login
    ADD verified BOOLEAN;

UPDATE security.login
    SET verified = TRUE
    WHERE verified IS NULL;

ALTER TABLE security.login
    ALTER COLUMN verified SET NOT NULL;

ALTER TABLE security.verification_token
    ADD CONSTRAINT uc_verification_token_id UNIQUE (id);

ALTER TABLE security.login
    ADD CONSTRAINT FK_LOGIN_ON_VERIFICATIONTOKEN FOREIGN KEY (verification_token_id) REFERENCES security.verification_token (id);

ALTER TABLE security.login_roles
    ADD CONSTRAINT FK_LOGIN_ROLES_ON_LOGIN FOREIGN KEY (login_id) REFERENCES security.login (id);

ALTER TABLE security.login_roles
    ADD CONSTRAINT FK_LOGIN_ROLES_ON_ROLE FOREIGN KEY (role_id) REFERENCES security.role (id);