DROP SCHEMA IF EXISTS security CASCADE;
CREATE SCHEMA security;

DROP TABLE IF EXISTS security.login CASCADE;
CREATE TABLE security.login
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_login PRIMARY KEY (id)
);

DROP TABLE IF EXISTS security.role CASCADE;
CREATE TABLE security.role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

DROP TABLE IF EXISTS security.login_roles CASCADE;
CREATE TABLE security.login_roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login_id BIGINT NOT NULL,
    role_id  BIGINT NOT NULL,
    CONSTRAINT pk_login_roles PRIMARY KEY (id)
);

INSERT INTO security."role" ("name") VALUES('ROLE_USER');
INSERT INTO security."role" ("name") VALUES('ROLE_ADMIN');

INSERT INTO security.login
(username, email, password)
VALUES('admin', 'admin@literaki.com', '$2a$10$Jyw.CWPZNxAxfafWD0fTwOy56/jIVtJkaW9ipws5pQoSDxoSKrP0O');

INSERT INTO security.login_roles(login_id,role_id) VALUES (1,2);