DROP TABLE IF EXISTS logs.logs CASCADE;
CREATE TABLE logs.logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    attempt_date    TIMESTAMP with time zone                NOT NULL,
    requestingip    VARCHAR(255)                            NOT NULL,
    requesting_user VARCHAR(255),
    type            INTEGER                                 NOT NULL,
    description     VARCHAR(255),
    CONSTRAINT pk_logs PRIMARY KEY (id)
);

ALTER TABLE logs.logs
    ADD CONSTRAINT uc_logs_id UNIQUE (id);